import { FarmRecipe } from '../../domain/entities/Recipe';

export const PRESET_RECIPE_DATABASE: FarmRecipe[] = [
  // 🇮🇳 Indian Farm Harvest Recipes (crafted from customer basket veggies)
  {
    id: 'ind-1',
    title: 'Desi Palak Dal Tadka (Spinach Lentil Curry)',
    description: 'Nourishing Indian yellow moong dal tempered with garlic, cumin, ghee, and fresh organic spinach from your Kshetriva harvest basket.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    servingSize: '2 Bowls (350g)',
    difficulty: 'Easy',
    category: 'Curry',
    cuisine: 'Indian',
    heroProduce: ['Organic Fresh Spinach'],
    ingredients: [
      { name: 'Organic Fresh Spinach', quantity: '250g chopped', isFromFarmBasket: true },
      { name: 'Yellow Moong Dal', quantity: '1 cup', isFromFarmBasket: false },
      { name: 'Pure Cow Ghee', quantity: '1 tbsp', isFromFarmBasket: false },
      { name: 'Cumin & Garlic', quantity: '1 tbsp minced', isFromFarmBasket: false },
      { name: 'Fresh Lemon Juice', quantity: '1 tbsp', isFromFarmBasket: true },
    ],
    instructions: [
      'Pressure cook yellow moong dal with turmeric, salt, and water until soft.',
      'Wilt finely chopped organic spinach in a pan with 1 tsp ghee for 2 minutes.',
      'In a small pan, prepare temper (tadka): heat ghee, add cumin seeds, garlic, and red chili.',
      'Stir wilted spinach into cooked dal and pour sizzling hot tadka over top. Garnish with lemon juice.'
    ],
    estimatedCalories: 280,
    macros: { protein: 18, carbs: 36, fat: 8 },
    healthBenefits: ['Rich in Plant Protein & Iron', 'High Bioavailable Folate', 'Gut-Soothing Spices'],
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: false,
    isFavorite: true,
    isSaved: true,
  },
  {
    id: 'ind-2',
    title: 'Gajar Methi Subzi (Heritage Carrot Dry Curry)',
    description: 'Traditional North Indian dry curry made with sweet heritage farm carrots, fenugreek leaves, ginger, and aromatic garam masala.',
    prepTimeMinutes: 8,
    cookTimeMinutes: 12,
    servings: 2,
    servingSize: '2 Bowls (280g)',
    difficulty: 'Easy',
    category: 'Sabzi',
    cuisine: 'Indian',
    heroProduce: ['Heritage Farm Carrots'],
    ingredients: [
      { name: 'Heritage Farm Carrots', quantity: '400g diced', isFromFarmBasket: true },
      { name: 'Fresh Methi / Fenugreek', quantity: '1/2 cup', isFromFarmBasket: true },
      { name: 'Mustard Oil', quantity: '1 tbsp', isFromFarmBasket: false },
      { name: 'Ginger & Green Chili', quantity: '1 tbsp chopped', isFromFarmBasket: true },
    ],
    instructions: [
      'Heat mustard oil in a kadhai until smoky, add cumin seeds and ginger.',
      'Add diced heritage carrots, turmeric, coriander powder, and salt. Cover and cook for 8 minutes.',
      'Add fresh chopped methi leaves and sauté uncovered for 4 minutes until carrots are tender and sweet.'
    ],
    estimatedCalories: 195,
    macros: { protein: 5, carbs: 24, fat: 9 },
    healthBenefits: ['Beta-Carotene Vision Support', 'Blood Sugar Regulation', 'High Fiber'],
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: false,
    isFavorite: false,
    isSaved: false,
  },
  {
    id: 'ind-3',
    title: 'Kadai Shimla Mirch (Spiced Bell Pepper Curry)',
    description: 'Vibrant red bell peppers tossed with roasted coriander seeds, tomatoes, kasuri methi, and cottage cheese.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    servingSize: '2 Servings (300g)',
    difficulty: 'Medium',
    category: 'Curry',
    cuisine: 'Indian',
    heroProduce: ['Red Bell Pepper'],
    ingredients: [
      { name: 'Red Bell Peppers', quantity: '2 large diced', isFromFarmBasket: true },
      { name: 'Organic Paneer', quantity: '150g cubed', isFromFarmBasket: false },
      { name: 'Tomato Gravy', quantity: '1 cup', isFromFarmBasket: true },
      { name: 'Kadai Masala Spices', quantity: '1 tbsp', isFromFarmBasket: false },
    ],
    instructions: [
      'Dry roast whole coriander seeds and dried red chilies, then crush coarsely.',
      'Sauté diced red bell peppers in ghee for 3 minutes until slightly blistered.',
      'Simmer tomato puree with kadai masala, add seared bell peppers and paneer cubes.',
      'Garnish with fresh coriander leaves and kasuri methi before serving.'
    ],
    estimatedCalories: 320,
    macros: { protein: 16, carbs: 18, fat: 20 },
    healthBenefits: ['Immune-Boosting Vitamin C', 'Calcium & Whey Protein', 'Antioxidant Boost'],
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: true,
    isFavorite: true,
    isSaved: true,
  },
  {
    id: 'ind-4',
    title: 'South Indian Broccoli Poriyal (Coconut Broccoli Stir-Fry)',
    description: 'Crisp farm broccoli florets tempered with mustard seeds, curry leaves, urad dal, and freshly grated coconut.',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 2,
    servingSize: '2 Portions (220g)',
    difficulty: 'Easy',
    category: 'Sabzi',
    cuisine: 'Indian',
    heroProduce: ['Broccoli Florets'],
    ingredients: [
      { name: 'Broccoli Florets', quantity: '400g small cuts', isFromFarmBasket: true },
      { name: 'Grated Fresh Coconut', quantity: '2 tbsp', isFromFarmBasket: false },
      { name: 'Coconut Oil', quantity: '1 tbsp', isFromFarmBasket: false },
      { name: 'Mustard Seeds & Curry Leaves', quantity: '1 tsp', isFromFarmBasket: true },
    ],
    instructions: [
      'Blanch broccoli florets in hot salted water for 2 minutes and drain.',
      'Heat coconut oil in a pan, add mustard seeds, urad dal, split green chili, and curry leaves.',
      'Toss blanched broccoli, sprinkle coconut oil, sea salt, and fresh grated coconut.',
      'Stir-fry on high flame for 2 minutes to retain crunch.'
    ],
    estimatedCalories: 175,
    macros: { protein: 7, carbs: 14, fat: 10 },
    healthBenefits: ['Detoxifying Sulforaphane', 'MCT Fats for Brain Fuel', 'Low Carbohydrate'],
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: false,
    isFavorite: false,
    isSaved: false,
  },
  {
    id: 'ind-5',
    title: 'Pudina Dhania Detox Chutney (Fresh Herb Chutney)',
    description: 'Refreshing bio-active green chutney made with farm mint, coriander, green chili, and roasted cumin.',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 4,
    servingSize: '4 tbsp (60g)',
    difficulty: 'Easy',
    category: 'Chutney',
    cuisine: 'Indian',
    heroProduce: ['Organic Fresh Mint & Basil'],
    ingredients: [
      { name: 'Organic Fresh Mint & Basil', quantity: '1 cup leaves', isFromFarmBasket: true },
      { name: 'Fresh Coriander', quantity: '1 cup', isFromFarmBasket: true },
      { name: 'Lemon Juice & Cumin', quantity: '1 tbsp', isFromFarmBasket: true },
      { name: 'Pink Himalayan Salt', quantity: '1/2 tsp', isFromFarmBasket: false },
    ],
    instructions: [
      'Wash fresh mint, coriander, and green chili thoroughly.',
      'Blend in a wet grinder with lemon juice, pink salt, and roasted cumin with 2 tbsp cold water.',
      'Serve as a digestive dip with meals or salad dressing.'
    ],
    estimatedCalories: 35,
    macros: { protein: 1, carbs: 5, fat: 0.5 },
    healthBenefits: ['Enzyme Digestive Support', 'Natural Alkalizing Dip', 'Zero Added Oil'],
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: false,
    isFavorite: false,
    isSaved: false,
  },

  // 🌍 Global Health Recipes
  {
    id: 'r1',
    title: 'Organic Spinach & Avocado Power Salad',
    description: 'Nutrient-rich farm-fresh spinach, avocado slices, heritage carrots, and toasted chia seeds with lemon olive oil dressing.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    servingSize: '2 Bowls (350g)',
    difficulty: 'Easy',
    category: 'Salad',
    cuisine: 'Global',
    heroProduce: ['Organic Fresh Spinach', 'Avocado', 'Heritage Farm Carrots'],
    ingredients: [
      { name: 'Organic Fresh Spinach', quantity: '150g', isFromFarmBasket: true },
      { name: 'Avocado', quantity: '1 medium', isFromFarmBasket: false },
      { name: 'Heritage Farm Carrots', quantity: '1 cup shredded', isFromFarmBasket: true },
      { name: 'Cold-Pressed Olive Oil', quantity: '1 tbsp', isFromFarmBasket: false },
    ],
    instructions: [
      'Wash fresh organic spinach florets under cold water and pat dry.',
      'Shred heritage carrots into thin ribbons and slice avocado into wedges.',
      'Toss greens in olive oil and lemon juice.'
    ],
    estimatedCalories: 340,
    macros: { protein: 8, carbs: 22, fat: 26 },
    healthBenefits: ['Rich in Folate & Vitamin K', 'Heart-Healthy Omega Fats'],
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: false,
    isFavorite: false,
    isSaved: false,
  },
  {
    id: 'r2',
    title: 'Wild Grilled Salmon & Quinoa Bowl',
    description: 'Herb-crusted wild salmon fillet served over fluffy brown quinoa and steamed broccoli florets.',
    prepTimeMinutes: 12,
    cookTimeMinutes: 15,
    servings: 1,
    servingSize: '1 Plate (400g)',
    difficulty: 'Medium',
    category: 'Main Dish',
    cuisine: 'Global',
    heroProduce: ['Broccoli Florets', 'Wild Salmon', 'Quinoa'],
    ingredients: [
      { name: 'Grilled Wild Salmon', quantity: '1 fillet (150g)', isFromFarmBasket: false },
      { name: 'Cooked Quinoa', quantity: '1 cup', isFromFarmBasket: true },
      { name: 'Broccoli Florets', quantity: '1 cup', isFromFarmBasket: true },
    ],
    instructions: [
      'Season wild salmon with sea salt and pan-sear for 4 minutes per side.',
      'Steam broccoli florets until tender-crisp.',
      'Plate cooked quinoa with seared salmon and broccoli.'
    ],
    estimatedCalories: 520,
    macros: { protein: 42, carbs: 44, fat: 18 },
    healthBenefits: ['High Muscle Recovery Protein', 'Omega-3 Fatty Acids'],
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80',
    isSubscriberExclusive: true,
    isFavorite: false,
    isSaved: false,
  },
];
